In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('Airline1.csv')

In [5]:
df[df['Source'].isnull()]

,ID,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
10660,10661,Vistara,21-03-2019,NaN,NaN,NaN,21:10,19-03-2026 00:05,2h 55m,non-stop,No info,NaN
10661,10662,Air India,09-05-2019,NaN,NaN,NaN,13:00,19:15,6h 15m,1 stop,No info,NaN

In [6]:
df.fillna({'Source': df['Source'].mode()[0]}, inplace=True)

In [8]:
df[df['Destination'].isnull()]
df.fillna({'Destination': df['Destination'].mode()[0]}, inplace=True)

In [11]:
df[df['Route'].isnull()]
df.fillna({'Route': df['Route'].mode()[0]}, inplace=True)

In [14]:
df[df['Price'].isnull()]
df.fillna({'Price': df['Price'].mean()}, inplace=True)

Empty DataFrame
Columns: [ID, Airline, Date_of_Journey, Source, Destination, Route, Dep_Time, Arrival_Time, Duration, Total_Stops, Additional_Info, Price]
Index: []